### PR TITLE
Add API to evict owner in etcd

### PR DESCRIPTION
**Pull request by xiekeyi98**
### What problem does this PR solve? 

Add API to evict invalid owner in etcd manually.
- [x] Show all information like `ETCDCTL_API=3 etcdctl --endpoints={PD address} get /tidb/ddl  --prefix` 
( `curl -L http://{PDHOST}:{PDPORT}/v3/kv/range -X POST -D '{"key":"{key}","range_end":"range_end"}'`)
- [x] delete owner campaign like ` ETCDCTL_API=3 ./etcdctl --endpoints={PD address} del /tidb/ddl/fg/owner/Lease_ID`)
( `curl -L http://{PDHOST}:{PDPORT}/v3/kv/deleterange -X POST -D '{"key":"{key}","range_end":""`)
- [x] delete schema version like `ETCDCTL_API=3 ./etcdctl --endpoints={PD address} del /tidb/ddl/all_schema_versions/DDL_ID` 
( `curl -L http://{PDHOST}:{PDPORT}/v3/kv/deleterange -X POST -D '{"key":"{key}","range_end":""`)

### CODE REVIEW

**Comment by brson** [comment]
Thanks for the PR @xiekeyi98. I don't know enough to do a full review on this but I do notice the PR checks in the binary tidb-ctl. Maybe that's not intended.

**Comment by jackysp** [comment]
Please remove the binary file in the commit.

**Comment by jackysp** [comment]
It is better to update the document in this PR. Maybe `make docs` will help.

**Comment by xiekeyi98** [comment]
Sorry for  adding binary...
I would have thought it will have the `.gitignore`.

I will make it more reviewable asap.

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by winkyao** [comment]
@jackysp Why this PR was merged with only one LGTM?

**Comment by jackysp** [comment]
emmm... 
There is no such rule for this repo...

**Pull request merged**
